# Hueman Theme settings
##
menu:
  Home: /
  Categories:
  About: /About/

customize:
  logo:
    width: 165
    height: 60
    url: images/logo-header.png
  theme_color: '#dd3333'
  highlight: atelier-cave-light
  sidebar: right # sidebar position, options: left, right
  thumbnail: false
  favicon: /favicon.png
  social_links:
    twitter: https://twitter.com/teknoglot
    github: https://github.com/stegenfeldt
    rss: /rss.xml
    
widgets:
  - recent_posts
  - category
  - tagcloud
  - links  

search:
  insight: true

comment:
  disqus: teknoglotse

share: default # options: jiathis, bdshare, addtoany, default

plugins:
  fancybox: true
  scrollloading: true
  google_analytics: UA-382656-8
  
miscellaneous:
  open_graph: # see http://ogp.me
    fb_app_id:
    fb_admins:
    twitter_id:
    google_plus:
  links:
    Atea: http://www.atea.se/